"""add user role

Revision ID: 93n6342a7gs4
Revises: 9c38b8075f62
Create Date: 2025-06-17 22:42:31.456345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93n6342a7gs4"
down_revision: Union[str, None] = "9c38b8075f62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    user_role_enum = sa.Enum("USER", "ADMIN", name="userrole")
    user_role_enum.create(op.get_bind())

    # Add role column with default value
    op.add_column(
        "users",
        sa.Column("role", user_role_enum, nullable=False, server_default="USER"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    sa.Enum("USER", "ADMIN", name="userrole").drop(op.get_bind())
    # ### end Alembic commands ###
