"""Add users

Revision ID: 9c38b8075f62
Revises: 94a1832a8b6a
Create Date: 2025-06-16 13:50:58.881909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c38b8075f62"
down_revision: Union[str, None] = "94a1832a8b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.execute("DELETE FROM contacts WHERE user_id IS NULL")
    op.alter_column("contacts", "user_id", nullable=False)
    op.drop_index("ix_contacts_email", table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    op.create_foreign_key(
        "fk_contacts_user_id",
        "contacts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contacts_user_id", "contacts", type_="foreignkey")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index("ix_contacts_email", "contacts", ["email"], unique=True)
    op.drop_column("contacts", "user_id")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
